name: Claude Chat

on:
  repository_dispatch:
    types: [claude_chat]

jobs:
  chat:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Call Claude API
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          # Escape special characters in prompts
          system_prompt=$(echo '${{ github.event.client_payload.system_prompt }}' | jq -R -s .)
          user_prompt=$(echo '${{ github.event.client_payload.user_prompt }}' | jq -R -s .)
          
          # Remove leading and trailing quotes added by jq
          system_prompt=${system_prompt:1:-1}
          user_prompt=${user_prompt:1:-1}
          
          # Construct the JSON payload
          json_payload=$(cat <<EOF
          {
            "model": "claude-3-opus-20240229",
            "max_tokens": 1024,
            "system": "${system_prompt}",
            "messages": [
              {
                "role": "user",
                "content": "${user_prompt}"
              }
            ]
          }
          EOF
          )
          
          echo "Debug - JSON payload:"
          echo "$json_payload"
          
          # Make the API call
          response=$(curl -s -X POST https://api.anthropic.com/v1/messages \
            -H "x-api-key: ${ANTHROPIC_API_KEY}" \
            -H "content-type: application/json" \
            -H "anthropic-version: 2023-06-01" \
            -d "$json_payload")
          
          echo "Debug - API response:"
          echo "$response"
          
          # Extract just the response text using jq
          response_text=$(echo $response | jq -r '.content[0].text // .error.message')
          
          # Create response JSON file with proper escaping
          echo "{\"response\": $(echo "$response_text" | jq -R -s .)}" > response.json
          
          echo "Created response.json:"
          cat response.json

      - name: Commit and push response
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add response.json
          git commit -m "Update Claude response [skip ci]"
          git push
