name: Claude Chat

on:
  repository_dispatch:
    types: [claude_chat]

jobs:
  chat:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Call Claude API
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          # Escape special characters in prompts
          system_prompt=$(echo '${{ github.event.client_payload.system_prompt }}' | sed 's/"/\\"/g')
          user_prompt=$(echo '${{ github.event.client_payload.user_prompt }}' | sed 's/"/\\"/g')
          
          response=$(curl -X POST https://api.anthropic.com/v1/messages \
            -H "x-api-key: $ANTHROPIC_API_KEY" \
            -H "content-type: application/json" \
            -H "anthropic-version: 2023-06-01" \
            -d "{
              \"model\": \"claude-3-opus-20240229\",
              \"max_tokens\": 1024,
              \"messages\": [
                {
                  \"role\": \"system\",
                  \"content\": \"$system_prompt\"
                },
                {
                  \"role\": \"user\",
                  \"content\": \"$user_prompt\"
                }
              ]
            }")
          
          # Create response JSON file
          echo "{\"response\": $(echo $response | jq '.content[0].text')}" > response.json

      - name: Commit and push response
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add response.json
          git commit -m "Update Claude response" || exit 0
          git push origin ${GITHUB_REF#refs/heads/}
